/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   main.c                                             :+:    :+:            */
/*                                                     +:+                    */
/*   By: rsteigen <rsteigen@student.codam.nl>         +#+                     */
/*                                                   +#+                      */
/*   Created: 2019/12/23 14:02:05 by rsteigen       #+#    #+#                */
/*   Updated: 2019/12/30 19:32:00 by rsteigen      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include "includes/printf.h"
#include <math.h>
#include <limits.h>
#define ULONG_MAX 0xFFFFFFFFUL

static void	check_f()
{
	double f;
	double g;
	long double lf;
	long double lf2;
	int rv1;
	int rv2;

	lf = INFINITY;
	rv1 = printf("{%+Lf}\n", lf);
	rv2 = ft_printf("[%+Lf]\n", lf);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("{% Lf}\n", lf);
	rv2 = ft_printf("[% Lf]\n", lf);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	lf = -0.0L;
	rv1 = printf("{%Lf}\n", lf);
	rv2 = ft_printf("[%Lf]\n", lf);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	lf2 = 0.0L;
	rv1 = printf("{%Lf}\n", lf2);
	rv2 = ft_printf("[%Lf]\n", lf2);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	f = -0.0;
	g = 0.0;
	rv1 = printf("\n%0#4.0f$\t(%%0#4.0f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%0#4.0f$\t(%%0#4.0f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%5.0#f$\t(%%5.0#f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%5.0#f$\t(%%5.0#f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%5.0f$\t(%%5.0f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%5.0f$\t(%%5.0f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.0#f$\t(%%.0#f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%.0#f$\t(%%.0#f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.0f$\t(%%.0f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%.0f$\t(%%.0f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%0#4.0f$\t(%%0#4.0f\t5.3\txx_printf)\n", 5.3);
	rv2 = ft_printf("\n%0#4.0f$\t(%%0#4.0f\t5.3\tft_printf)\n", 5.3);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%#1.0f$\t(%%#1.0f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%#1.0f$\t(%%#1.0f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%#2.0f$\t(%%#2.0f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%#2.0f$\t(%%#2.0f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%#0.0f$\t(%%#0.0f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%#0.0f$\t(%%#0.0f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%#.0f$\t(%%#.0f\t-0.0\txx_printf)\n", f);
	rv2 = ft_printf("\n%#.0f$\t(%%#.0f\t-0.0\tft_printf)\n", f);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%0#4.0f$\t(%%0#4.0f\t0.0\txx_printf)\n", g);
	rv2 = ft_printf("\n%0#4.0f$\t(%%0#4.0f\t0.0\tft_printf)\n", g);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%5.0#f$\t(%%5.0#f\t0.0\txx_printf)\n", g);
	rv2 = ft_printf("\n%5.0#f$\t(%%5.0#f\t0.0\tft_printf)\n", g);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%5.0f$\t(%%5.0f\t0.0\txx_printf)\n", g);
	rv2 = ft_printf("\n%5.0f$\t(%%5.0f\t0.0\tft_printf)\n", g);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.0#f$\t(%%.0#f\t0.0\txx_printf)\n", g);
	rv2 = ft_printf("\n%.0#f$\t(%%.0#f\t0.0\tft_printf)\n", g);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.0f$\t(%%.0f\t0.0\txx_printf)\n", g);
	rv2 = ft_printf("\n%.0f$\t(%%.0f\t0.0\tft_printf)\n", g);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	long double lf_nan;
	long double lf_inf;
	int retp;
	int retftp;
	lf_nan = NAN;
	retftp = ft_printf("[% 8Lf]\n", lf_nan);
	printf("return: %d\n", retftp);
	retp = printf("{% 8Lf}\n", lf_nan);
	printf("return: %d\n", retp);
	retftp = ft_printf("[%Lf]\n", lf_nan);
	printf("return: %d\n", retftp);
	retp = printf("{%Lf}\n", lf_nan);
	printf("return: %d\n", retp);
	lf_inf = INFINITY;
	rv1 = printf("{%+Lf}\n", lf_inf);
	rv2 = ft_printf("[%+Lf]\n", lf_inf);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);

	rv1 = printf("\n%.0f$\t(%%.0f\t0.0\txx_printf)\n", 0.0);
	rv2 = ft_printf("\n%.0f$\t(%%.0f\t0.0\tft_printf)\n", 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n% 10.0f$\t(%% 10.0f\t0/0.0\txx_printf)\n", 0 / 0.0);
	rv2 = ft_printf("\n% 10.0f$\t(%% 10.0f\t0/0.0\tft_printf)\n", 0 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%10f$\t(%%10f\t0/0.0\txx_printf)\n", 0 / 0.0);
	rv2 = ft_printf("\n%10f$\t(%%10f\t0/0.0\tft_printf)\n", 0 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n% 10f$\t(%% 10f\t0/0.0\txx_printf)\n", 0 / 0.0);
	rv2 = ft_printf("\n% 10f$\t(%% 10f\t0/0.0\tft_printf)\n", 0 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n% 8f$\t(%% 8f\t0/0.0\txx_printf)\n", 0 / 0.0);
	rv2 = ft_printf("\n% 8f$\t(%% 8f\t0/0.0\tft_printf)\n", 0 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%8f$\t(%%8f\t0/0.0\txx_printf)\n", 0 / 0.0);
	rv2 = ft_printf("\n%8f$\t(%%8f\t0/0.0\tft_printf)\n", 0 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.0f$\t(%%.0f\t1/0.0\txx_printf)\n", 1 / 0.0);
	rv2 = ft_printf("\n%.0f$\t(%%.0f\t1/0.0\tft_printf)\n", 1 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.0f$\t(%%.0f\t-1/0.0\txx_printf)\n", -1 / 0.0);
	rv2 = ft_printf("\n%.0f$\t(%%.0f\t-1/0.0\tft_printf)\n", -1 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.0f$\t(%%.0f\t-45/0.0\txx_printf)\n", -45 / 0.0);
	rv2 = ft_printf("\n%.0f$\t(%%.0f\t-45/0.0\tft_printf)\n", -45 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n% .1f$\t(%% .1f\t0.0\txx_printf)\n", 0.0);
	rv2 = ft_printf("\n% .1f$\t(%% .1f\t0.0\tft_printf)\n", 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n% f$\t(%% f\t0.0\txx_printf)\n", 0.0);
	rv2 = ft_printf("\n% f$\t(%% f\t0.0\tft_printf)\n", 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.1f$\t(%%.1f\t0/0.0\txx_printf)\n", 0 / 0.0);
	rv2 = ft_printf("\n%.1f$\t(%%.1f\t0/0.0\tft_printf)\n", 0 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.1f$\t(%%.1f\t1/0.0\txx_printf)\n", 1 / 0.0);
	rv2 = ft_printf("\n%.1f$\t(%%.1f\t1/0.0\tft_printf)\n", 1 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%.1f$\t(%%.1f\t-1/0.0\txx_printf)\n", -1 / 0.0);
	rv2 = ft_printf("\n%.1f$\t(%%.1f\t-1/0.0\tft_printf)\n", -1 / 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);	
	rv1 = printf("\n%f$\t(%%f\tsrt(-1)\txx_printf)\n", sqrt(-1));
	rv2 = ft_printf("\n%f$\t(%%f\tsrt(-1)\tft_printf)\n", sqrt(-1));
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);

	rv1 = printf("\n%0.0f$\n(%%0.0f\t0\txx_printf)\n", -3.123);
	rv2 = ft_printf("\n%0.0f$\n(%%0.0f\t0\tft_printf)\n", -3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%015.0f$\n(%%015.0f\t0\txx_printf)\n", -3.123);
	rv2 = ft_printf("\n%015.0f$\n(%%015.0f\t0\tft_printf)\n", -3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%+015.0f$\n(%%+015.0f\t0\txx_printf)\n", 3.123);
	rv2 = ft_printf("\n%+015.0f$\n(%%+015.0f\t0\tft_printf)\n", 3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n% 015.0f$\n(%% 015.0f\t0\txx_printf)\n", 3.123);
	rv2 = ft_printf("\n% 015.0f$\n(%% 015.0f\t0\tft_printf)\n", 3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%+15.0f$\n(%%+15.0f\t0\txx_printf)\n", 3.123);
	rv2 = ft_printf("\n%+15.0f$\n(%%+15.0f\t0\tft_printf)\n", 3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n% 15.0f$\n(%% 15.0f\t0\txx_printf)\n", 3.123);
	rv2 = ft_printf("\n% 15.0f$\n(%% 15.0f\t0\tft_printf)\n", 3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%+0.0f$\n(%%+0.0f\t0\txx_printf)\n", 3.123);
	rv2 = ft_printf("\n%+0.0f$\n(%%+0.0f\t0\tft_printf)\n", 3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n% 0.0f$\n(%% 0.0f\t0\txx_printf)\n", 3.123);
	rv2 = ft_printf("\n% 0.0f$\n(%% 0.0f\t0\tft_printf)\n", 3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%0.0f$\n(%%0.0f\t0\txx_printf)\n", 0.0);
	rv2 = ft_printf("\n%0.0f$\n(%%0.0f\t0\tft_printf)\n", 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%0.0f$\n(%%0.0f\t0\txx_printf)\n", -0.0);
	rv2 = ft_printf("\n%0.0f$\n(%%0.0f\t0\tft_printf)\n", -0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%06.0f$\n(%%06.0f\t0\txx_printf)\n", 0.0);
	rv2 = ft_printf("\n%06.0f$\n(%%06.0f\t0\tft_printf)\n", 0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	rv1 = printf("\n%06.0f$\n(%%06.0f\t0\txx_printf)\n", -0.0);
	rv2 = ft_printf("\n%06.0f$\n(%%06.0f\t0\tft_printf)\n", -0.0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
}

static void	check_s(void)
{
	char *str = "hoi";
	printf("\n%*5d$\t(%%*5d\t-15, 34\tprintf)\n", -15, 34);
	ft_printf("%*5d$\t(%%*5d\t-15, 34\tft_printf)\n", -15, 34);
	printf("\n%*5d$\t(%%*5d\t15, 34\tprintf)\n", 15, 34);
	ft_printf("%*5d$\t(%%*5d\t15, 34\tft_printf)\n", 15, 34);
	printf("\n%*d$\t(%%*d\t15, 34\tprintf)\n", 15, 34);
	ft_printf("%*d$\t(%%*d\t15, 34\tft_printf)\n", 15, 34);
	printf("\n%s$\t(%%s\tstr\tprintf)\n", str);
	ft_printf("%s$\t(%%s\tstr\tft_printf)\n", str);
	printf("\n%*s$\t(%%*s 5\tstr\tprintf)\n", 5, str);
	ft_printf("%*s$\t(%%*s 5\tstr\tft_printf)\n", 5, str);
	printf("\n%*s$\t(%%*s -5\tstr\tprintf)\n", -5, str);
	ft_printf("%*s$\t(%%*s -5\tstr\tft_printf)\n", -5, str);
	printf("\n%*s$\t(%%*10s -5\tstr\tprintf)\n", -5, str);
	ft_printf("%*s$\t(%%*10s -5\tstr\tft_printf)\n", -5, str);
	printf("\n%*7s$\t(%%*7s -5\tstr\tprintf)\n", -5, str);
	ft_printf("%*7s$\t(%%*7s -5\tstr\tft_printf)\n", -5, str);
	printf("\n%*7s$\t(%%*7s 5\tstr\tprintf)\n", 5, str);
	ft_printf("%*7s$\t(%%*7s 5\tstr\tft_printf)\n", 5, str);
	printf("\n%*50s$\t(%%*50s -13\tstr\tprintf)\n", -13, str);
	ft_printf("%*50s$\t(%%*50s -13\tstr\tft_printf)\n", -13, str);
	printf("\n%*50s$\t(%%*50s 13\tstr\tprintf)\n", 13, str);
	ft_printf("%*50s$\t(%%*50s 13\tstr\tft_printf)\n", 13, str);
	printf("\n%7*s$\t(%%7*s 5\tstr\tprintf)\n", 5, str);
	ft_printf("%7*s$\t(%%7*s 5\tstr\tft_printf)\n", 5, str);
	printf("\n%7*s$\t(%%7*s -5\tstr\tprintf)\n", -5, str);
	ft_printf("%7*s$\t(%%7*s -5\tstr\tft_printf)\n", -5, str);
	char *str1 = "hello";
	printf("\n%%8*s\n", 2, str1);
	printf("{%8*s}\n", 2, str1);
	ft_printf("[%8*s]\n", 2, str1);
	printf("\n%%8*s\n", 2, str1);
	printf("{%8*s}\n", 2, str1);
	ft_printf("[%8*s]\n", 2, str1);
	printf("\n%%8.*s\n", 2, str1);
	printf("{%8.*s}\n", 2, str1);
	ft_printf("[%8.*s]\n", 2, str1);
	printf("\n%%8.2s\n", str1);
	printf("{%8.2s}\n", str1);
	ft_printf("[%8.2s]\n", str1);
	printf("\n%%3.8s\n", str1);
	printf("{%3.8s}\n", str1);
	ft_printf("[%3.8s]\n", str1);
	printf("\n%%8.0s\n", str1);
	printf("{%8.0s}\n", str1);
	ft_printf("[%8.0s]\n", str1);
	printf("\n%%8.-1s\n", str1);
	printf("{%8.-1s}\n", str1);
	ft_printf("[%8.-1s]\n", str1);

	printf("return_pf:\t(%%*50s, -13, NULL)\t%d\n", printf("-pf\n%50*s$\n", -13, NULL));
	printf("return_fpf:\t(%%*50s, -13, NULL)\t%d\n", ft_printf("fpf\n%50*s$\n", -13, NULL));
	printf("\n");
	printf("return_pf:\t(%%50*s, -13, NULL)\t%d\n", printf("-pf\n%50*s$\n", -13, NULL));
	printf("return_fpf:\t(%%50*s, -13, NULL)\t%d\n", ft_printf("fpf\n%50*s$\n", -13, NULL));
	printf("\n");
	printf("\n%*50s$\t(%%*50s -2\tstr\tprintf)\n", -2, str);
	ft_printf("%*50s$\t(%%*50s -2\tstr\tft_printf)\n", -2, str);
	printf("\n%0-*s$\t(%%0-*s 5\tstr\tprintf)\n", 5, str);
	ft_printf("%0-*s$\t(%%0-*s 5\tstr\tft_printf)\n", 5, str);
	printf("return_pf:\t(%%50*s, 3, NULL)\t%d\n", printf("-pf\n%50*s$\n", 3, NULL));
	printf("return_fpf:\t(%%50*s, 3, NULL)\t%d\n", ft_printf("fpf\n%50*s$\n", 3, NULL));
	printf("\n");
	printf("return_pf:\t(%%50*s, -3, NULL)\t%d\n", printf("-pf\n%50*s$\n", -3, NULL));
	printf("return_fpf:\t(%%50*s, -3, NULL)\t%d\n", ft_printf("fpf\n%50*s$\n", -3, NULL));
	printf("\n");
	printf("return_pf:\t(%%50*s, 13, NULL)\t%d\n", printf("-pf\n%50*s$\n", 13, NULL));
	printf("return_fpf:\t(%%50*s, 13, NULL)\t%d\n", ft_printf("fpf\n%50*s$\n", 13, NULL));
	printf("\n");
	printf("return_pf:\t(%%50*s, -13, NULL)\t%d\n", printf("-pf\n%50*s$\n", -13, NULL));
	printf("return_fpf:\t(%%50*s, -13, NULL)\t%d\n", ft_printf("fpf\n%50*s$\n", -13, NULL));
	printf("\n");
	printf("return_pf:\t(%%50.*s, 3, NULL)\t%d\n", printf("-pf\n%50.*s$\n", 3, NULL));
	printf("return_fpf:\t(%%50.*s, 3, NULL)\t%d\n", ft_printf("fpf\n%50.*s$\n", 3, NULL));
	printf("\n");
	printf("return_pf:\t(%%50.*s, -3, NULL)\t%d\n", printf("-pf\n%50.*s$\n", -3, NULL));
	printf("return_fpf:\t(%%50.*s, -3, NULL)\t%d\n", ft_printf("fpf\n%50.*s$\n", -3, NULL));
	printf("\n");
}

static void check_x(void)
{
	int d;
	d = 0;
	printf("\n%5.0X$\n(%%5.0X\t0\tprintf)\n", d);
	ft_printf("%5.0X$\n(%%5.0X\t0\tft_printf)\n", d);
	printf("\n%0.0x$\n(%%0.0x\t0\tprintf)\n", d);
	ft_printf("%0.0x$\n(%%0.0x\t0\tft_printf)\n", d);
	printf("\n%0.0o$\n(%%0.0o\t0\tprintf)\n", d);
	ft_printf("%0.0o$\n(%%0.0o\t0\tft_printf)\n", d);
	printf("\n%0.0d$\n(%%0.0d\t0\tprintf)\n", d);
	ft_printf("%0.0d$\n(%%0.0d\t0\tft_printf)\n", d);
	printf("\n%0.0f$\n(%%0.0f\t0\tprintf)\n", d);
	ft_printf("%0.0f$\n(%%0.0f\t0\tft_printf)\n", d);
	printf("\n%0.0e$\n(%%0.0e\t0\tprintf)\n", d);
	ft_printf("%0.0e$\n(%%0.0e\t0\tft_printf)\n", d);
	printf("\n%0.0p$\n(%%0.0p\t0\tprintf)\n", d);
	ft_printf("%0.0p$\n(%%0.0p\t0\tft_printf)\n", d);
	printf("\n%0p$\n(%%0p\t0\tprintf)\n", d);
	ft_printf("%0p$\n(%%0p\t0\tft_printf)\n", d);
	printf("\n%#0.0p$\n(%%#0.0p\t0\tprintf)\n", d);
	ft_printf("%#0.0p$\n(%%#0.0p\t0\tft_printf)\n", d);
	printf("\n%0.0s$\n(%%0.0s\t0\tprintf)\n", d);
	ft_printf("%0.0s$\n(%%0.0s\t0\tft_printf)\n", d);
	printf("\n%0.0c$\n(%%0.0c\t0\tprintf)\n", d);
	ft_printf("%0.0c$\n(%%0.0c\t0\tft_printf)\n", d);
	printf("\n%0.0u$\n(%%0.0u\t0\tprintf)\n", d);
	ft_printf("%0.0u$\n(%%0.0u\t0\tft_printf)\n", d);
	d = 4242;
	printf("\n%0.5X$\n(%%0.5X\t0\tprintf)\n", d);
	ft_printf("%0.5X$\n(%%0.5X\t0\tft_printf)\n", d);
	printf("\n%13.15x$\n(%%13.15x\t0\tprintf)\n", d);
	ft_printf("%13.15x$\n(%%13.15x\t0\tft_printf)\n", d);
	printf("\n%13.5x$\n(%%13.5x\t0\tprintf)\n", d);
	ft_printf("%13.5x$\n(%%13.5x\t0\tft_printf)\n", d);
	printf("\n%3.4x$\n(%%3.4x\t0\tprintf)\n", d);
	ft_printf("%3.4x$\n(%%3.4x\t0\tft_printf)\n", d);
	printf("\n%#25X$\n(%%#25X\t0\tprintf)\n", d);
	ft_printf("%#25X$\n(%%#25X\t0\tft_printf)\n", d);
	printf("\n%#25p$\n(%%#25p\t0\tprintf)\n", d);
	ft_printf("%#25p$\n(%%#25p\t0\tft_printf)\n", d);
	printf("\n%#25X$\n(%%#25X\t0\tprintf)\n", 1);
	ft_printf("%#25X$\n(%%#25X\t0\tft_printf)\n", 1);
	printf("\n%#25.0X$\n(%%#25.0X\t0\tprintf)\n", 45);
	ft_printf("%#25.0X$\n(%%#25.0X\t0\tft_printf)\n", 45);

	// printf("return_pf:\t(%%-015x (str1))\t%d\n", printf("%-015x$\n", 381));
	// printf("return_fpf:\t(%%-015x (str1))\t%d\n", ft_printf("%-015x$\n", 381));
	// printf("\n");
	// printf("return_pf:\t(%%15x (str1))\t%d\n", printf("%15x$\n", 381));
	// printf("return_fpf:\t(%%15x (str1))\t%d\n", ft_printf("%15x$\n", 381));
	// printf("\n");
	// printf("return_pf:\t(%%0*x (12, str1)\t%d\n", printf("%0*x$\n", 12, 381));
	// printf("return_fpf:\t(%%0*x 12, str1)\t%d\n", ft_printf("%0*x$\n", 12, 381));
	// printf("\n");
	// printf("return_pf:\t(%%0-*x (12, str1)\t%d\n", printf("%0-*x$\n", 12, 381));
	// printf("return_fpf:\t(%%0-*x 12, str1)\t%d\n", ft_printf("%0-*x$\n", 12, 381));
	// printf("\n");
	// printf("return_pf:\t(%%+-0*x (12, str1))\t%d\n", printf("%+-0*x$\n", 12, 381));
	// printf("return_fpf:\t(%%+-0*x (12, str1))\t%d\n", ft_printf("%+-0*x$\n", 12, 381));
	// printf("\n");
	// printf("return_pf:\t(%%x (0))\t%d\n", printf("%x\n", 0));
	// printf("return_fpf:\t(%%x (0))\t%d\n", ft_printf("%x\n", 0));
	// printf("\n");
	// printf("return_pf:\t(%%9x)\t%d\n", printf("%9x\n", 482));
	// printf("return_fpf:\t(%%9x)\t%d\n", ft_printf("%9x\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%#9.0x)\t%d\n", printf("\n%#9.0x\n", 482));
	// printf("return_fpf:\t(%%#9.0x)\t%d\n", ft_printf("%#9.0x\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%9.3X)\t%d\n", printf("%9.3X$\n", 482));
	// printf("return_fpf:\t(%%9.3X)\t%d\n", ft_printf("%9.3X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%9X)\t%d\n", printf("%9X\n", 482));
	// printf("return_fpf:\t(%%9X)\t%d\n", ft_printf("%9X\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%.5X)\t%d\n", printf("%.5X\n", 32));
	// printf("return_fpf:\t(%%.5X)\t%d\n", ft_printf("%.5X\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%-.5X)\t%d\n", printf("%-.5X$\n", 32));
	// printf("return_fpf:\t(%%-.5X)\t%d\n", ft_printf("%-.5X$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%--.5X)\t%d\n", printf("%--.5X$\n", 32));
	// printf("return_fpf:\t(%%--.5X)\t%d\n", ft_printf("%--.5X$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%-.5x)\t%d\n", printf("%-.5x$\n", 32));
	// printf("return_fpf:\t(%%-.5x)\t%d\n", ft_printf("%-.5x$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%--.5x)\t%d\n", printf("%--.5x$\n", 32));
	// printf("return_fpf:\t(%%--.5x)\t%d\n", ft_printf("%--.5x$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%.5X)\t%d\n", printf("%.5X$\n", 32));
	// printf("return_fpf:\t(%%.5X)\t%d\n", ft_printf("%.5X$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%.5X)\t%d\n", printf("%.5X$\n", 32));
	// printf("return_fpf:\t(%%.5X)\t%d\n", ft_printf("%.5X$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%.5x)\t%d\n", printf("%.5x$\n", 32));
	// printf("return_fpf:\t(%%.5x)\t%d\n", ft_printf("%.5x$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%.5x)\t%d\n", printf("%.5x$\n", 32));
	// printf("return_fpf:\t(%%.5x)\t%d\n", ft_printf("%.5x$\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%.X)\t%d\n", printf("%.X\n", 32));
	// printf("return_fpf:\t(%%.X)\t%d\n", ft_printf("%.X\n", 32));
	// printf("\n");
	// printf("return_pf:\t(%%9.0X)\t%d\n", printf("%9.0X\n", 482));
	// printf("return_fpf:\t(%%9.0X)\t%d\n", ft_printf("%9.0X\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%9X)\t%d\n", printf("%9X$\n", 482));
	// printf("return_fpf:\t(%%9X)\t%d\n", ft_printf("%9X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%9-X)\t%d\n", printf("%9-X$\n", 482));
	// printf("return_fpf:\t(%%9-X)\t%d\n", ft_printf("%9-X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%-9X)\t%d\n", printf("%-9X$\n", 482));
	// printf("return_fpf:\t(%%-9X)\t%d\n", ft_printf("%-9X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%X)\t%d\n", printf("%X\n", 5));
	// printf("return_fpf:\t(%%X)\t%d\n", ft_printf("%X\n", 5));
	// printf("\n");
	// printf("return_pf:\t(%%X)\t%d\n", printf("%X\n", 5 + 1));
	// printf("return_fpf:\t(%%X)\t%d\n", ft_printf("%X\n", 5 + 1));
	// printf("\n");
	// printf("return_pf:\t(%%X)\t%d\n", printf("%X\n", 5 + 2));
	// printf("return_fpf:\t(%%X)\t%d\n", ft_printf("%X\n", 5 + 2));
	// printf("\n");
	// printf("return_pf:\t(%%X)\t%d\n", printf("%X\n", 5 + 12));
	// printf("return_fpf:\t(%%X)\t%d\n", ft_printf("%X\n", 5 + 12));
	// printf("\n");

	// printf("\n%%015#x (printf)\n");
	// printf("\n%015#x.\n", 15);
	// ft_printf("%015#x.\n", 15);
	// char *str1 = "Rmrn";
	// printf("\n%%0*#x (printf value: 12)\n%0*#x.\n", 12, str1);
	// ft_printf("%0*#x.\n", 12, str1);
	// printf("\n%%-*#x (printf, value: 10)\n%-*#x.\n", 10, str1);
	// ft_printf("%-*#x.\n", 10, str1);
	// printf("return_pf:\t(%%#09X)\t%d\n", printf("\n%#09X$\n", 482));
	// printf("return_fpf:\t(%%#09X)\t%d\n", ft_printf("%#09X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%09X)\t%d\n", printf("\n%09X$\n", 482));
	// printf("return_fpf:\t(%%09X)\t%d\n", ft_printf("%09X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%#09p)\t%d\n", printf("\n%#09p$\n", 482));
	// printf("return_fpf:\t(%%#09p)\t%d\n", ft_printf("%#09p$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%09p)\t%d\n", printf("\n%09p$\n", 482));
	// printf("return_fpf:\t(%%09p)\t%d\n", ft_printf("%09p$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%#09.10X)\t%d\n", printf("\n%#09.10X$\n", 482));
	// printf("return_fpf:\t(%%#09.10X)\t%d\n", ft_printf("%#09.10X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%#09.5X)\t%d\n", printf("\n%#09.5X$\n", 482));
	// printf("return_fpf:\t(%%#09.5X)\t%d\n", ft_printf("%#09.5X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%#09.0X)\t%d\n", printf("\n%#09.0X$\n", 482));
	// printf("return_fpf:\t(%%#09.0X)\t%d\n", ft_printf("%#09.0X$\n", 482));
	// printf("\n");
	// printf("return_pf:\t(%%#09.1X)\t%d\n", printf("\n%#09.1X$\n", 482));
	// printf("return_fpf:\t(%%#09.1X)\t%d\n", ft_printf("%#09.1X$\n", 482));
	// printf("\n");
}

static void	check_d(void)
{
	int d;
	d = -666666;
	printf("**d begin**\n");
	printf("{%d}\n", -0);
	ft_printf("[%d]\n", -0);
	printf("{%.5d}\n", -0);
	ft_printf("[%.5d]\n", -0);
	printf("{%.5d}\n", d);
	ft_printf("[%.5d]\n", d);
	printf("{%.6d}\n", d);
	ft_printf("[%.6d]\n", d);
	printf("{%.#6d}\n", d);
	ft_printf("[%.#6d]\n", d);
	printf("{%.15d}\n", d);
	ft_printf("[%.15d]\n", d);
	printf("{%+05#d}\n", -7);
	ft_printf("[%+05#d]\n", -7);
	d = -4242;
	printf("{%.5d}\n", d);
	ft_printf("[%.5d]\n", d);
	printf("{%5.12d}\n", d);
	ft_printf("[%5.12d]\n", d);
	printf("{%12.7d}\n", d);
	ft_printf("[%12.7d]\n", d);
	printf("{%.7d}\n", d);
	ft_printf("[%.7d]\n", d);
	printf("{%5.12d}\n", d);
	ft_printf("[%5.12d]\n", d);
	printf("{%.5d}\n", d);
	ft_printf("[%.5d]\n", d);
	printf("{%12d}\n", d);
	ft_printf("[%12d]\n", d);
	printf("**u begin**\n");
	int u = 4242;
	printf("{%12.5u}\n", u);
	ft_printf("[%12.5u]\n", u);
	printf("{%.5u}\n", u);
	ft_printf("[%.5u]\n", u);
	printf("{%.6u}\n", u);
	ft_printf("[%.6u]\n", u);
	printf("{%.#6u}\n", u);
	ft_printf("[%.#6u]\n", u);
	printf("{%.15u}\n", u);
	ft_printf("[%.15u]\n", u);
	printf("{%+05#u}\n", -7);
	ft_printf("[%+05#u]\n", -7);
	printf("{%12.7u}\n", u);
	ft_printf("[%12.7u]\n", u);
	printf("{%.7u}\n", u);
	ft_printf("[%.7u]\n", u);
	printf("{%5.12u}\n", u);
	ft_printf("[%5.12u]\n", u);
	printf("{%.5u}\n", u);
	ft_printf("[%.5u]\n", u);
	printf("{%12u}\n", u);
	ft_printf("[%12u]\n", u);

	printf("**x begin**\n");
	printf("{%12.5x}\n", u);
	ft_printf("[%12.5x]\n", u);
	printf("{%.5x}\n", u);
	ft_printf("[%.5x]\n", u);
	printf("{%.6x}\n", u);
	ft_printf("[%.6x]\n", u);
	printf("{%.#6x}\n", u);
	ft_printf("[%.#6x]\n", u);
	printf("{%.15x}\n", u);
	ft_printf("[%.15x]\n", u);
	printf("\n%%+05#x\n");
	printf("{%+05#x}\n", -7);
	ft_printf("[%+05#x]\n", -7);
	printf("\n%%+5#x\n");
	printf("{%+5#x}\n", -7);
	ft_printf("[%+5#x]\n", -7);
	printf("\n%%05#x\n");
	printf("{%05#x}\n", -7);
	ft_printf("[%05#x]\n", -7);
	printf("\n%%5#x\n");
	printf("{%5#x}\n", -7);
	ft_printf("[%5#x]\n", -7);
	printf("\n%% 05#x\n");
	printf("{% 05#x}\n", -7);
	ft_printf("[% 05#x]\n", -7);

	printf("{%12.7x}\n", u);
	ft_printf("[%12.7x]\n", u);
	printf("{%.7x}\n", u);
	ft_printf("[%.7x]\n", u);
	printf("{%5.12x}\n", u);
	ft_printf("[%5.12x]\n", u);
	printf("{%.5x}\n", u);
	ft_printf("[%.5x]\n", u);
	printf("{%12x}\n", u);
	ft_printf("[%12x]\n", u);

	long l = 9223372036854775807;
	printf("{%-5.*ld}\n", 32, l);
	ft_printf("[%-5.*ld]\n", 32, l);
	printf("**o begin**\n");
	printf("{%12.5o}\n", u);
	ft_printf("[%12.5o]\n", u);
	printf("{%.5o}\n", u);
	ft_printf("[%.5o]\n", u);
	printf("{%.6o}\n", u);
	ft_printf("[%.6o]\n", u);
	printf("{%.#6o}\n", u);
	ft_printf("[%.#6o]\n", u);
	printf("{%.15o}\n", u);
	ft_printf("[%.15o]\n", u);
	printf("{%+05#o}\n", -7);
	ft_printf("[%+05#o]\n", -7);

	printf("{%12.7o}\n", u);
	ft_printf("[%12.7o]\n", u);
	printf("{%.7o}\n", u);
	ft_printf("[%.7o]\n", u);
	printf("{%5.12o}\n", u);
	ft_printf("[%5.12o]\n", u);
	printf("{%.5o}\n", u);
	ft_printf("[%.5o]\n", u);
	printf("{%12o}\n", u);
	ft_printf("[%12o]\n", u);
	printf("{%.#5o}\n", u);
	ft_printf("[%.#5o]\n", u);
	printf("{%#12o}\n", u);
	ft_printf("[%#12o]\n", u);

	u = 0.0;
	printf("**f begin**\n");
	printf("{%12.5f}\n", u);
	ft_printf("[%12.5f]\n", u);
	printf("{%.5f}\n", u);
	ft_printf("[%.5f]\n", u);
	printf("\n%%.6f\n");
	printf("{%.6f}\n", u);
	ft_printf("[%.6f]\n", u);
	printf("\n%%.f\n");
	printf("{%.f}\n", u);
	ft_printf("[%.f]\n", u);
	printf("\n%%6.f\n");
	printf("{%6.f}\n", u);
	ft_printf("[%6.f]\n", u);
	printf("\n%%#.6f\n");
	printf("{%#.6f}\n", u);
	ft_printf("[%#.6f]\n", u);
	printf("\n%%.#6f\n");
	printf("{%.#6f}\n", u);
	ft_printf("[%.#6f]\n", u);
	printf("\n%%.0#6f\n");
	printf("{%.0#6f}\n", u);
	ft_printf("[%.0#6f]\n", u);
	printf("\n%%. 6f\n");
	printf("{%. 6f}\n", u);
	ft_printf("[%. 6f]\n", u);
	printf("\n%%.06f\n");
	printf("{%.06f}\n", u);
	ft_printf("[%.06f]\n", u);
	printf("\n%%.#5f\n");
	printf("{%.#5f}\n", u);
	ft_printf("[%.#5f]\n", u);
	printf("\n%%.#5f\n");
	printf("{%#.5f}\n", u);
	ft_printf("[%#.5f]\n", u);
	int rt1;
	int rt2;
	printf("\n\n%%.#V5f\n");
	rt1 = printf("{%.#V5f eind zin}\n", u);
	rt2 = ft_printf("[%.#V5f einde zin]\n", u);
	printf("Return printf: %d\nReturn ft_printf: %d\n", rt1, rt2);
	printf("\n\n%%.&6f\n");
	rt1 = printf("{%.&6f} einde zin\n", u);
	rt2 = ft_printf("[%.&6f] einde zin\n", u);
	printf("Return printf: %d\nReturn ft_printf: %d\n", rt1, rt2);
	printf("{%.15f}\n", u);
	ft_printf("[%.15f]\n", u);
	rt1 = printf("{%+05#f}\n", -7);
	rt2 = ft_printf("[%+05#f]\n", -7);
	printf("Return printf: %d\nReturn ft_printf: %d\n", rt1, rt2);
	printf("{%12.7f}\n", u);
	ft_printf("[%12.7f]\n", u);
	printf("{%.7f}\n", u);
	ft_printf("[%.7f]\n", u);
	printf("{%5.12f}\n", u);
	ft_printf("[%5.12f]\n", u);
	printf("{%.5f}\n", u);
	ft_printf("[%.5f]\n", u);
	printf("{%12f}\n", u);
	ft_printf("[%12f]\n", u);
	printf("{%#12f}\n", u);
	ft_printf("[%#12f]\n", u);
}

static void	check_o(void)
{
	printf("\n%0.0o$\n(%%0.0o\t0\tprintf)\n", 0);
	ft_printf("%0.0o$\n(%%0.0o\t0\tft_printf)\n", 0);
	int d;
	d = 42;
	printf("%0-5hho$\n", (unsigned char)d);
	ft_printf("%0-5hho$\n", (unsigned char)d);
	printf("%0-5hhd$\n", (unsigned char)d);
	ft_printf("%0-5hhd$\n", (unsigned char)d);
	printf("%0-5hhu$\n", (unsigned char)d);
	ft_printf("%0-5hhu$\n", (unsigned char)d);
	printf("%0-5hhx$\n", (unsigned char)d);
	ft_printf("%0-5hhx$\n", (unsigned char)d);
	long l;
	l = 9223372036854775807;
	printf("{%-5.*lo}\n", 32, l);
	ft_printf("[%-5.*lo]\n", 32, l);
	printf("{%-22.*lo}\n", 25, l);
	ft_printf("[%-22.*lo]\n", 25, l);
	l = 42;
	printf("o{%5.*lo}\n", -5, l);
	ft_printf("o[%5.*lo]\n", -5, l);
	printf("d{%5.*ld}\n", -5, l);
	ft_printf("d[%5.*ld]\n", -5, l);
	printf("u{%5.*lu}\n", -5, l);
	ft_printf("u[%5.*lu]\n", -5, l);
	printf("x{%5.*lx}\n", -5, l);
	ft_printf("x[%5.*lx]\n", -5, l);
	printf("o{%5lo}\n", l);
	ft_printf("o[%5lo]\n", l);
	printf("d{%5ld}\n", l);
	ft_printf("d[%5ld]\n", l);
	printf("u{%5lu}\n", l);
	ft_printf("u[%5lu]\n", l);
	printf("x{%5lx}\n", l);
	ft_printf("x[%5lx]\n", l);
	printf("o{%.*lo}\n", -5, l);
	ft_printf("o[%.*lo]\n", -5, l);
	printf("{%.*ld}\n", -5, l);
	ft_printf("[%.*ld]\n", -5, l);
	printf("{%.*lu}\n", -5, l);
	ft_printf("[%.*lu]\n", -5, l);
	printf("{%.*lx}\n", -5, l);
	ft_printf("[%.*lx]\n", -5, l);
	printf("{%*lo}\n", -5, l);
	ft_printf("[%*lo]\n", -5, l);
	printf("{%*ld}\n", -5, l);
	ft_printf("[%*ld]\n", -5, l);
	printf("{%*lu}\n", -5, l);
	ft_printf("[%*lu]\n", -5, l);
	printf("{%*lx}\n", -5, l);
	ft_printf("[%*lx]\n", -5, l);
	printf("{%.-5lo}\n", l);
	ft_printf("[%.-5lo]\n", l);
	printf("{%.-5ld}\n", l);
	ft_printf("[%.-5ld]\n", l);
	printf("{%.-5lu}\n", l);
	ft_printf("[%.-5lu]\n", l);
	printf("{%.-5lx}\n", l);
	ft_printf("[%.-5lx]\n", l);
	printf("{%.5lo}\n", l);
	ft_printf("[%.5lo]\n", l);
	printf("{%.5ld}\n", l);
	ft_printf("[%.5ld]\n", l);
	printf("{%.5lu}\n", l);
	ft_printf("[%.5lu]\n", l);
	printf("{%.5lx}\n", l);
	ft_printf("[%.5lx]\n", l);
	l = 5.0;
	printf("{%15.*lf}\n", -15, l);
	ft_printf("[%15.*lf]\n", -15, l);
	int u = 56;
	printf("**o begin**\n");
	printf("{%12.5o}\n", u);
	ft_printf("[%12.5o]\n", u);
	printf("{%.5o}\n", u);
	ft_printf("[%.5o]\n", u);
	printf("{%.6o}\n", u);
	ft_printf("[%.6o]\n", u);
	printf("{%.#6o}\n", u);
	ft_printf("[%.#6o]\n", u);
	printf("{%.15o}\n", u);
	ft_printf("[%.15o]\n", u);
	printf("{%+05#o}\n", -7);
	ft_printf("[%+05#o]\n", -7);

	printf("{%12.7o}\n", u);
	ft_printf("[%12.7o]\n", u);
	printf("{%.7o}\n", u);
	ft_printf("[%.7o]\n", u);
	printf("{%5.12o}\n", u);
	ft_printf("[%5.12o]\n", u);
	printf("{%.5o}\n", u);
	ft_printf("[%.5o]\n", u);
	printf("{%12o}\n", u);
	ft_printf("[%12o]\n", u);
	printf("{%.#5o}\n", u);
	ft_printf("[%.#5o]\n", u);
	printf("{%#12o}\n", u);
	ft_printf("[%#12o]\n", u);
	unsigned long ulong_max;
	ulong_max = ULONG_MAX;
	printf("%%#09.0o (482)\n");
	printf("\nreturn_pf:\t(%%#09.0o (482))\t%d\n", printf("%#09.0o$", 482));
	printf("return_fpf:\t(%%#09.0o (482))\t%d\n", ft_printf("%#09.0o$\n", 482));
	printf("%%lo (ulong_max)\n");	
	printf("\nreturn_pf:\t(%%lo)\t%d\n", printf("%lo$", ulong_max));
	printf("return_fpf:\t(%%lo)\t%d\n", ft_printf("%lo$\n", ulong_max));
	printf("%%llo (ulong_max + 10)\n");	
	printf("\nreturn_pf:\t(%%llo)\t%d\n", printf("%llo$", ulong_max + 10));
	printf("return_fpf:\t(%%llo)\t%d\n", ft_printf("%llo$\n", ulong_max + 10));
	printf("%%#09.0o (482)\n");	
	printf("\nreturn_pf:\t(%%#09.0o)\t%d\n", printf("%#09.0o$", 482));
	printf("return_fpf:\t(%%#09.0o)\t%d\n", ft_printf("%#09.0o$\n", 482));
	printf("%%09.0o (482)\n");	
	printf("\nreturn_pf:\t(%%09.0o$)\t%d\n", printf("%09.0o$", 482));
	printf("return_fpf:\t(%%09.0o$)\t%d\n", ft_printf("%09.0o$\n", 482));
	printf("%%09o (482)\n");	
	printf("\nreturn_pf:\t(%%09o$)\t%d\n", printf("%09o$", 482));
	printf("return_fpf:\t(%%09o$)\t%d\n", ft_printf("%09o$\n", 482));
	printf("%%09.*o (0, 482)\n");	
	printf("\nreturn_pf:\t(%%09.*o$ 0, 482)\t%d\n", printf("%09.*o$", 0, 482));
	printf("return_fpf:\t(%%09.*o$ 0, 482)\t%d\n", ft_printf("%09.*o$\n", 0, 482));
	printf("\nAsterisk WIDTH #\n");
	printf("\nprintf\t%%0*#o$ (11, 798)\n%0*#o$\n", 11, 798);
	ft_printf("%0*#o$\n", 11, 798);
	printf("\nprintf\t%%0*o (11, 798)\n%0*o$\n", 11, 798);
	ft_printf("%0*o$\n", 11, 798);
	printf("\nprintf\t%%0.*o (11, 798)\n%0.*o$\n", 11, 798);
	ft_printf("%0.*o$\n", 11, 798);
	printf("%%09.0o (482)\n");	
	printf("\nreturn:\t(%%09.0d$)\t%d\n", printf("%09.0d$", 482));
	printf("\nreturn:\t(%%09.0d$)\t%d\n", ft_printf("%09.0d$", 482));
	printf("\nprintf\t%%0*d (11, 798)\n%0*d$\n", 11, 798);
	ft_printf("%0*d$\n", 11, 798);
	printf("\nprintf\t%%+8o$\t(327) width: 8, flag: +\n%+8o$\n", 327);
	ft_printf("%+8o$\n", 327);
	printf("\nprintf\t%%+8o\t(0) width: 8, flag: +\n%+8o$\n", 0);
	ft_printf("%+8o$\n", 0);
	printf("\nprintf\t%%+8o\t(-327) width: 8, flag: +\n%+8o$\n", -327);
	ft_printf("%+8o$\n", -327);
	printf("\nprintf\t%%+8o\t(56) flag: + (visible), align left\n%+-o$\n", 56);
	ft_printf("%+-o$\n", 56);
	printf("\nprintf\t%% -o\t(998)\
	invisible plus ' ', align left '-'\n% -o$\n", 998);
	ft_printf("% -o$\n", 998);
}

static void	check_p(void)
{
	char *str1 = "Roos";
	ft_printf("[%p]\n", str1);
	printf("{%p}\n", str1);
	printf("return_pf:\t(%%-015p (str1))\t%d\n", printf("%-015p$\n", str1));
	printf("return_fpf:\t(%%-015p (str1))\t%d\n", ft_printf("%-015p$\n", str1));
	printf("\n");
	printf("return_pf:\t(%%15p (str1))\t%d\n", printf("%15p$\n", str1));
	printf("return_fpf:\t(%%15p (str1))\t%d\n", ft_printf("%15p$\n", str1));
	printf("\n");
	printf("return_pf:\t(%%0*p (12, str1)\t%d\n", printf("%0*p$\n", 12, str1));
	printf("return_fpf:\t(%%0*p 12, str1)\t%d\n", ft_printf("%0*p$\n", 12, str1));
	printf("\n");
	printf("return_pf:\t(%%0-*p (12, str1)\t%d\n", printf("%0-*p$\n", 12, str1));
	printf("return_fpf:\t(%%0-*p 12, str1)\t%d\n", ft_printf("%0-*p$\n", 12, str1));
	printf("\n");
	printf("return_pf:\t(%%+-0*p (12, str1))\t%d\n", printf("%+-0*p$\n", 12, str1));
	printf("return_fpf:\t(%%+-0*p (12, str1))\t%d\n", ft_printf("%+-0*p$\n", 12, str1));
	printf("\n");
	printf("return_pf:\t(%%p (0))\t%d\n", printf("%p\n", 0));
	printf("return_fpf:\t(%%p (0))\t%d\n", ft_printf("%p\n", 0));
	printf("\n");
	printf("return_pf:\t(%%9p)\t%d\n", printf("%9p\n", 482));
	printf("return_fpf:\t(%%9p)\t%d\n", ft_printf("%9p\n", 482));
	printf("\n");
	printf("return_pf:\t(%%#9.0p)\t%d\n", printf("%#9.0p\n", 482));
	printf("return_fpf:\t(%%#9.0p)\t%d\n", ft_printf("%#9.0p\n", 482));
	printf("\n");
	printf("return_pf:\t(%%09.3p)\t%d\n", printf("%09.3p$\n", 482));
	printf("return_fpf:\t(%%09.3p)\t%d\n", ft_printf("%09.3p$\n", 482));
	printf("\n");
	printf("return_pf:\t(%%9.3p)\t%d\n", printf("%9.3p$\n", 482));
	printf("return_fpf:\t(%%9.3p)\t%d\n", ft_printf("%9.3p$\n", 482));
	printf("\n");
	printf("return_pf:\t(%%9.3x)\t%d\n", printf("%9.3x$\n", 482));
	printf("return_fpf:\t(%%9.3x)\t%d\n", ft_printf("%9.3x$\n", 482));
	printf("\n");
	printf("return_pf:\t(%%#9.3x)\t%d\n", printf("%#9.3x$\n", 482));
	printf("return_fpf:\t(%%#9.3x)\t%d\n", ft_printf("%#9.3x$\n", 482));
	printf("\n");
	printf("return_pf:\t(%%9p)\t%d\n", printf("%9p\n", 482));
	printf("return_fpf:\t(%%9p)\t%d\n", ft_printf("%9p\n", 482));
	printf("\n");
	printf("return_pf:\t(%%.5p)\t%d\n", printf("%.5p\n", 32));
	printf("return_fpf:\t(%%.5p)\t%d\n", ft_printf("%.5p\n", 32));
	printf("\n");
	printf("return_pf:\t(%%.5x)\t%d\n", printf("%.5x\n", 32));
	printf("return_fpf:\t(%%.5x)\t%d\n", ft_printf("%.5x\n", 32));
	printf("\n");
	printf("return_pf:\t(%%-.5p)\t%d\n", printf("%-.5p\n", 32));
	printf("return_fpf:\t(%%-.5p)\t%d\n", ft_printf("%-.5p\n", 32));
	printf("\n");
	printf("return_pf:\t(%%-.5x)\t%d\n", printf("%-.5x\n", 32));
	printf("return_fpf:\t(%%-.5x)\t%d\n", ft_printf("%-.5x\n", 32));
	printf("\n");
	printf("return_pf:\t(%%--.5p)\t%d\n", printf("%--.5p\n", 32));
	printf("return_fpf:\t(%%--.5p)\t%d\n", ft_printf("%--.5p\n", 32));
	printf("\n");
	printf("return_pf:\t(%%--.5x)\t%d\n", printf("%--.5x\n", 32));
	printf("return_fpf:\t(%%--.5x)\t%d\n", ft_printf("%--.5x\n", 32));
	printf("\n");
	printf("return_pf:\t(%%#--.5x)\t%d\n", printf("%#--.5x\n", 32));
	printf("return_fpf:\t(%%#--.5x)\t%d\n", ft_printf("%#--.5x\n", 32));
	printf("\n");
	printf("return_pf:\t(%%.p)\t%d\n", printf("%.p\n", 32));
	printf("return_fpf:\t(%%.p)\t%d\n", ft_printf("%.p\n", 32));
	printf("\n");
	printf("return_pf:\t(%%9.0p)\t%d\n", printf("%9.0p\n", 482));
	printf("return_fpf:\t(%%9.0p)\t%d\n", ft_printf("%9.0p\n", 482));
	printf("\n");
	printf("return_pf:\t(%%19.5p)\t%d\n", printf("%19.5p\n", 482));
	printf("return_fpf:\t(%%19.5p)\t%d\n", ft_printf("%19.5p\n", 482));
	printf("\n");
	printf("return_pf:\t(%%9p)\t%d\n", printf("%9p\n", 482));
	printf("return_fpf:\t(%%9p)\t%d\n", ft_printf("%9p\n", 482));
	printf("\n");
	printf("return_pf:\t(%%p)\t%d\n", printf("%p\n", LONG_MAX));
	printf("return_fpf:\t(%%p)\t%d\n", ft_printf("%p\n", LONG_MAX));
	printf("\n");
	printf("return_pf:\t(%%p)\t%d\n", printf("%p\n", LONG_MAX + 1));
	printf("return_fpf:\t(%%p)\t%d\n", ft_printf("%p\n", LONG_MAX + 1));
	printf("\n");
	printf("return_pf:\t(%%p)\t%d\n", printf("%p\n", LONG_MAX + 2));
	printf("return_fpf:\t(%%p)\t%d\n", ft_printf("%p\n", LONG_MAX + 2));
	printf("\n");
	printf("return_pf:\t(%%p)\t%d\n", printf("%p\n", LONG_MAX + 12));
	printf("return_fpf:\t(%%p)\t%d\n", ft_printf("%p\n", LONG_MAX + 12));
	printf("\n");
}

static void	check_uu(void)
{
	unsigned int u = 4242;
	long l = 42;
	int rt1;
	int rt2;
	rt1 = printf("{%.0u}\n", u);
	rt2 = ft_printf("[%.0u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("u{%5.*lu}\n", -5, l);
	rt2 = ft_printf("u[%5.*lu]\n", -5, l);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("u{%5lu}\n", l);
	rt2 = ft_printf("u[%5lu]\n", l);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.*lu}\n", -5, l);
	rt2 = ft_printf("[%.*lu]\n", -5, l);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%*lu}\n", -5, l);
	rt2 = ft_printf("[%*lu]\n", -5, l);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.5lu}\n", l);
	rt2 = ft_printf("[%.5lu]\n", l);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%12.5u}\n", u);
	rt2 = ft_printf("[%12.5u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.5u}\n", u);
	rt2 = ft_printf("[%.5u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.6u}\n", u);
	rt2 = ft_printf("[%.6u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.#6u}\n", u);
	rt2 = ft_printf("[%.#6u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.15u}\n", u);
	rt2 = ft_printf("[%.15u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%+05#u}\n", -7);
	rt2 = ft_printf("[%+05#u]\n", -7);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%12.7u}\n", u);
	rt2 = ft_printf("[%12.7u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.7u}\n", u);
	rt2 = ft_printf("[%.7u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%5.12u}\n", u);
	rt2 = ft_printf("[%5.12u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%.5u}\n", u);
	rt2 = ft_printf("[%.5u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
	rt1 = printf("{%12u}\n", u);
	rt2 = ft_printf("[%12u]\n", u);
	printf("ret printf: %d\nret ft_printf: %d\n", rt1, rt2);
}

static void check_e(void)
{
	int rv1;
	int rv2;

	printf("De asterisk werkt niet goed.");
	printf("\nprintf\t%%#*e\t(18, 7.3412)\n%#*e\n", 18, 7.3412);
	ft_printf("%#*e\n", 18, 7.3412);
	printf("\nprintf\t%%#-*e\t(0, 7.3412)\n%#-*e\n", 0, 7.3412);
	ft_printf("%#-*e\n", 0, 7.3412);
	printf("\n- asterisk pointing to width value NO ZERO: 0");
	printf("\nprintf\t%%-*e\t(0, 7.3412)\n%-*e\n", 0, 7.3412);
	ft_printf("%-*e\n", 0, 7.3412);
	printf("\n- asterisk pointing to width value NO ZERO: 4");
	printf("\nprintf\t%%-*e\t(4, 7.3412)\n%-*e\n", 4, 7.3412);
	ft_printf("%-*e\n", 4, 7.3412);
	printf("\n- asterisk pointing to width value NO ZERO: 18");
	printf("\nprintf\t%%-*e\t(18, 7.3412)\n%-*e\n", 18, 7.3412);
	ft_printf("%-*e\n", 18, 7.3412);
	printf("\n- asterisk pointing to width value WITH ZERO: 18");
	printf("\nprintf\t%%-0*e\t(18, -7.3412)\n%-0*e\n", 18, -7.3412);
	ft_printf("%-0*e\n", 18, -7.3412);
	rv1 = printf("\n%0.0e$\n(%%0.0e\t0\txx_printf)\n", -3.123);
	rv2 = ft_printf("\n%0.0e$\n(%%0.0e\t0\tft_printf)\n", -3.123);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	printf("\n%015.0e$\n(%%015.0e\t0\tprintf)\n", -3.123);
	ft_printf("%015.0e$\n(%%015.0e\t0\tft_printf)\n", -3.123);
	printf("\n%15.0e$\n(%%15.0e\t0\tprintf)\n", -3.123);
	ft_printf("%15.0e$\n(%%15.0e\t0\tft_printf)\n", -3.123);
	printf("\n%+015.0e$\n(%%+015.0e\t0\tprintf)\n", 3.123);
	ft_printf("%+015.0e$\n(%%+015.0e\t0\tft_printf)\n", 3.123);
	printf("\n%+15.0e$\n(%%+15.0e\t0\tprintf)\n", 3.123);
	ft_printf("%+15.0e$\n(%%+15.0e\t0\tft_printf)\n", 3.123);
	printf("\n%+0.0e$\n(%%+0.0e\t0\tprintf)\n", 3.123);
	ft_printf("%+0.0e$\n(%%+0.0e\t0\tft_printf)\n", 3.123);
	printf("\n%+10.0e$\n(%%+10.0e\t0\tprintf)\n", 3.123);
	ft_printf("%+10.0e$\n(%%+10.0e\t0\tft_printf)\n", 3.123);
	printf("\n% 0.0e$\n(%% 0.0e\t0\tprintf)\n", 3.123);
	ft_printf("% 0.0e$\n(%% 0.0e\t0\tft_printf)\n", 3.123);
	printf("\n%0.0e$\n(%%0.0e\t0\tprintf)\n", 0.0);
	ft_printf("%0.0e$\n(%%0.0e\t0\tft_printf)\n", 0.0);
	printf("\n%0.0e$\n(%%0.0e\t0\tprintf)\n", -0.0);
	ft_printf("%0.0e$\n(%%0.0e\t0\tft_printf)\n", -0.0);
	printf("\n%0.0e$\n(%%06.0e\t0\tprintf)\n", 0.0);
	ft_printf("%0.0e$\n(%%06.0e\t0\tft_printf)\n", 0.0);
	printf("\n%0.0e$\n(%%06.0e\t0\tprintf)\n", -0.0);
	ft_printf("%0.0e$\n(%%06.0e\t0\tft_printf)\n", -0.0);
	rv1 = printf("{%d}\n", -0);
	rv2 = ft_printf("[%d]\n", -0);
	printf("printf: %d\nft_printf: %d\n", rv1, rv2);
	printf("{%.5d}\n", -0);
	ft_printf("[%.5d]\n", -0);
	printf("{%f}\n", 1.0/0.0);
	ft_printf("[%f]\n", 1.0/0.0);
	printf("{%f}\n", 0.0/1.0);
	ft_printf("[%f]\n", 0.0/1.0);
	printf("undefined {%.5d}\n", 1/0);
	ft_printf("undefined [%.5d]\n", 1/0);
	printf("{%.5d}\n", 0/1);
	ft_printf("[%.5d]\n", 0/1);
}

static void	d_mistakes(void)
{
	printf("{%+05#d}\n", 7);
	ft_printf("[%+05#d]\n", 7);
	printf("return_pf:\t(%%+.0d, 5)\t%d\n", printf("%+.0d$\n", 5));
	printf("return_fpf:\t(%%+.0d, 5)\t%d\n", ft_printf("%+.0d$\n", 5));
	printf("\n");
	ft_printf("printf %%+-5d, 0\n");
	printf("%+-5d$\n", 0);
	ft_printf("%+-5d$\n", 0);
	printf("{% 05#d}\n", 7);
	ft_printf("[% 05#d]\n", 7);
	printf("return_pf:\t(%% .0d, 5)\t%d\n", printf("% .0d$\n", 5));
	printf("return_fpf:\t(%% .0d, 5)\t%d\n", ft_printf("% .0d$\n", 5));
	printf("\n");
	ft_printf("printf %% -5d, 0\n");
	printf("% -5d$\n", 0);
	ft_printf("% -5d$\n", 0);
}

static void	empty_precision(void)
{
	int d;
	d = 0;
	printf("\n%%-2.d\n");
	printf("{%-2.d}\n", d);
	ft_printf("[%-2.d]\n", d);
	printf("\n%%-2.0d\n");
	printf("{%-2.0d}\n", d);
	ft_printf("[%-2.0d]\n", d);

	printf("\n%%-2.e\n");
	printf("{%-2.e}\n", d);
	ft_printf("[%-2.e]\n", d);
	printf("\n%%-2.0e\n");
	printf("{%-2.0e}\n", d);
	ft_printf("[%-2.0e]\n", d);

	printf("\n%%-2.f\n");
	printf("{%-2.f}\n", d);
	ft_printf("[%-2.f]\n", d);
	printf("\n%%-2.0f\n");
	printf("{%-2.0f}\n", d);
	ft_printf("[%-2.0f]\n", d);

	printf("\n%%-2.o\n");
	printf("{%-2.o}\n", d);
	ft_printf("[%-2.o]\n", d);
	printf("\n%%-2.0o\n");
	printf("{%-2.0o}\n", d);
	ft_printf("[%-2.0o]\n", d);

	printf("\n%%-2.u\n");
	printf("{%-2.u}\n", d);
	ft_printf("[%-2.u]\n", d);
	printf("\n%%-2.0u\n");
	printf("{%-2.0u}\n", d);
	ft_printf("[%-2.0u]\n", d);

	printf("\n%%-2.x\n");
	printf("{%-2.x}\n", d);
	ft_printf("[%-2.x]\n", d);
	printf("\n%%-2.0x\n");
	printf("{%-2.0x}\n", d);
	ft_printf("[%-2.0x]\n", d);

	printf("\n%%-2.p\n");
	printf("{%-2.p}\n", d);
	ft_printf("[%-2.p]\n", d);
	printf("\n%%-2.0p\n");
	printf("{%-2.0p}\n", d);
	ft_printf("[%-2.0p]\n", d);

	printf("\n%%5*d, 15, 3\n", 15, 3);
	printf("%5*d\n", 15, 3);
	ft_printf("%5*d\n", 15, 3);

	printf("\n%%15*d, 5, 3\n", 5, 3);
	printf("%15*d\n", 5, 3);
	ft_printf("%15*d\n", 5, 3);
	int X;
	X = 0;
	printf("{%#25X}\n", X);
	ft_printf("[%#25X]\n", X);
	printf("{%#25X (3)}\n", 3);
	ft_printf("[%#25X (3)]\n", 3);
	printf("{%#25d}\n", X);
	ft_printf("[%#25d]\n", X);
	printf("{%#25e}\n", X);
	ft_printf("[%#25e]\n", X);
	printf("{%#25u}\n", X);
	ft_printf("[%#25u]\n", X);
	printf("{%#25o}\n", X);
	ft_printf("[%#25o]\n", X);
	printf("{%#25p}\n", X);
	ft_printf("[%#25p]\n", X);
	printf("{%#25f}\n", 0.0);
	ft_printf("[%#25f]\n", 0.0);
}

void	weird_float(void)
{
	double f;
	f = -0.0;
	printf("\n{%+0#*.*f}\n", 4, 0, f);
	ft_printf("[%+0#*.*f]\n", 4, 0, f);
	printf("\n{%+0*.*f}\n", 4, 0, f);
	ft_printf("[%+0*.*f]\n", 4, 0, f);
	printf("\n{%+0#.**f}\n", 4, 10, f);
	ft_printf("[%+0#.**f]\n", 4, 10, f);
	printf("\n{%+0.**f}\n", 4, 10, f);
	ft_printf("[%+0.**f]\n", 4, 10, f);
	printf("\n{%+0#.**f}\n", 4, -10, f);
	ft_printf("[%+0#.**f]\n", 4, -10, f);
	printf("\n{%+0.**f}\n", 4, -10, f);
	ft_printf("[%+0.**f]\n", 4, -10, f);
	printf("\n{%+0#.**f}\n", -4, 10, f);
	ft_printf("[%+0#.**f]\n", -4, 10, f);
	printf("\n{%+0.**f}\n", -4, 10, f);
	ft_printf("[%+0.**f]\n", -4, 10, f);

	printf("\n{%4+0#.*f}\n", 0, f);
	ft_printf("[%4+0#.*f]\n", 0, f);
	printf("\n{%4+0.*f}\n", 0, f);
	ft_printf("[%4+0.*f]\n", 0, f);
	printf("\n{%#f}\n", f);
	ft_printf("[%#f]\n", f);
	printf("\n{%+#f}\n", f);
	ft_printf("[%+#f]\n", f);
	printf("\n{%.0#f}\n", f);
	ft_printf("[%.0#f]\n", f);
	printf("\n{%0#f}\n", f);
	ft_printf("[%0#f]\n", f);
	printf("\n{%4+0.*f}\n", 0, f);
	ft_printf("[%4+0.*f]\n", 0, f);

	f = 35.5;
	printf("\n{%.0f}\n", f);
	ft_printf("[%.0f]\n", f);
	long double lf;
	lf = INFINITY * -1;
	printf("\n{% 8Lf}\n", lf);
	ft_printf("[% 8Lf]\n", lf);
	lf = INFINITY;
	printf("\n{%+8Lf}\n", lf);
	ft_printf("[%+8Lf]\n", lf);
	lf = NAN;
	printf("\n{%+Lf}\n", lf);
	ft_printf("[%+Lf]\n", lf);
}

void	final_countdown(void)
{
	int X;
	X = 0;
	ft_printf("[%#25X]\n", X);
	printf("{%#25X}\n", X);	
	ft_printf("[%25X]\n", X);
	printf("{%25X}\n", X);
	long double f;
	f = INFINITY * -1;
	ft_printf("[%+Lf]\n", f);
	printf("{%+Lf}\n", f);
	ft_printf("[% Lf]\n", f);
	printf("{% Lf}\n", f);
}

int		main(void)
{
	check_f();	//main	//links
	// check_s();	//main	//check
	// check_x();	//main	//
	// check_d();	//main	//
	// check_o();	//main	//
	// check_p();	//main	//
	// check_uu();	//main	//
	// check_e();	//main	//
	// d_mistakes();
	// empty_precision();
	// weird_float();
	// final_countdown();
	return (0);
}
